# Generated by Django 5.2.11 on 2026-02-05 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Para/Altın Kodu')),
                ('name', models.CharField(max_length=50, verbose_name='Görünen Ad')),
                ('buy_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Alış Fiyatı')),
                ('sell_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Satış Fiyatı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
            ],
            options={
                'verbose_name': 'Finansal Veri',
                'verbose_name_plural': 'Finansal Veriler',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL Yolu (Otomatik)')),
                ('description', models.TextField(blank=True, verbose_name='Ürün Açıklaması')),
                ('weight_gram', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Gramaj')),
                ('purity', models.IntegerField(choices=[(8, '8 Ayar'), (14, '14 Ayar'), (22, '22 Ayar'), (24, '24 Ayar (Has)')], verbose_name='Ayar')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='İşçilik Ücreti (TL)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ürün Görseli')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayında mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField(verbose_name='İçerik')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Haber Görseli')),
                ('category', models.CharField(choices=[('news', 'Piyasa Haberi'), ('note', 'Piyasa Notu')], default='news', max_length=10, verbose_name='Kategori')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayında')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'verbose_name': 'Haber/Not',
                'verbose_name_plural': 'Haberler ve Notlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
