# Generated by Django 5.2.11 on 2026-02-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='labor_cost',
        ),
        migrations.AddField(
            model_name='product',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Kar Marjı (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purity',
            field=models.IntegerField(choices=[(24, '24 Ayar (Has)'), (22, '22 Ayar'), (14, '14 Ayar'), (8, '8 Ayar')], verbose_name='Ayar'),
        ),
    ]
