# Generated by Django 5.2.11 on 2026-02-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_labor_cost_product_profit_margin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialdata',
            options={'verbose_name': 'Finansal Veri (Otomatik)', 'verbose_name_plural': 'Finansal Veriler'},
        ),
        migrations.AddField(
            model_name='financialdata',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Satış Kar Marjı (%)'),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='buy_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Piyasa Alış'),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='sell_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Piyasa Satış'),
        ),
    ]
